language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  - PACKAGE="jackline" OCAML_VERSION=4.01 EXTRA_REMOTES="https://github.com/hannesm/xmpp-opam.git"
  - PACKAGE="jackline" OCAML_VERSION=latest EXTRA_REMOTES="https://github.com/hannesm/xmpp-opam.git"
notifications:
  email: false
